### ISSUE TITLE
[Android] Weex runtime error

### ISSUE THREAD

**Issue by PymZoR** [weexteam/weex-hackernews#12]
Hi,
I built the project using `npm run build:weex && npm run copy:android`, and opened the project with Android studio.
Runtime details:
> Android studio 2.2.2
> Android emulator Nexus_5X_API_25:5554

Got the following errors (sorry for the format - tried my best): 

> 12-30 14:46:34.406 3580-3580/com.example.weex.hackernews E/weex: initWXBridge HackAssertionException com.taobao.weex.utils.WXHack$HackDeclaration$HackAssertionException: java.lang.ClassNotFoundException: com.taobao.weex.devtools.debug.DebugServerProxy
> ....at com.taobao.weex.utils.WXHack.into(WXHack.java:232)
> ....at com.taobao.weex.bridge.WXBridgeManager.initWXBridge(WXBridgeManager.java:365)
> ....at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:338)
> ....at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:347)
> ....at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:223)
> ....at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:212)
> ....at com.example.weex.hackernews.WXApplication.onCreate(WXApplication.java:19)
> ....at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
> ....at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
> ....at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
> ....at android.app.ActivityThread.-wrap2(ActivityThread.java)
> ....at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
> ....at android.os.Handler.dispatchMessage(Handler.java:102)
> ....at android.os.Looper.loop(Looper.java:154)
> ....at android.app.ActivityThread.main(ActivityThread.java:6119)
> ....at java.lang.reflect.Method.invoke(Native Method)
> ....at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
> ....at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
> 
> ..Caused by: java.lang.ClassNotFoundException: com.taobao.weex.devtools.debug.DebugServerProxy
> ....at java.lang.Class.classForName(Native Method)
> ....at java.lang.Class.forName(Class.java:400)
> ....at java.lang.Class.forName(Class.java:326)
> ....at com.taobao.weex.utils.WXHack.into(WXHack.java:230)
> ....at com.taobao.weex.bridge.WXBridgeManager.initWXBridge(WXBridgeManager.java:365) 
> ....at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:338) 
> ....at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:347) 
> ....at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:223) 
> ....at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:212) 
> ....at com.example.weex.hackernews.WXApplication.onCreate(WXApplication.java:19) 
> ....at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370) 
> ....at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024) 
> ....at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403) 
> ....at android.app.ActivityThread.-wrap2(ActivityThread.java) 
> ....at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
> ....at android.os.Handler.dispatchMessage(Handler.java:102) 
> ....at android.os.Looper.loop(Looper.java:154) 
> ....at android.app.ActivityThread.main(ActivityThread.java:6119) 
> ....at java.lang.reflect.Method.invoke(Native Method) 
> ....at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
> ....at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
> 
> ..Caused by: java.lang.ClassNotFoundException: Didn't find class "com.taobao.weex.devtools.debug.DebugServerProxy" on path: DexPathList[[dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-support-annotations-24.1.1_5aab62e234ebbdf55225f20b51a994cada9b1f60-classes.dex", dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-picasso-2.5.2_7fd10b4381d2583d30c407c74f236c5ad7d52458-classes.dex", dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-internal_impl-24.1.1_f6efbad1ab482711795f9f08ce9da8aab1814f93-classes.dex", dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-fastjson-1.1.46.android_7d67bd7281cd159c45a9468e523539db9ded4d42-classes.dex", dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-com.android.support-support-vector-drawable-24.1.1_a224abd2f5aee3db556f2f91f6810877b0035254-classes.dex", dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-com.android.support-support-v4-24.1.1_afc89397e0e7838f134e13dab9dbdafda4dfd1ca-classes.dex", dex file "/data/data/com.example.weex.hackernews/files/instant-run/dex/slice-com.android.support-recyclerview-v7-24.1.1_10baed5406a176d0f372a850e182767e4ee07b21-classes.dex", dex file "/data/data/com.example.weex.hackernews/file
> 12-30 14:46:34.568 3580-3773/com.example.weex.hackernews E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
> 12-30 14:46:34.569 3580-3773/com.example.weex.hackernews E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
> 12-30 14:46:34.584 3580-3773/com.example.weex.hackernews E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
> 12-30 14:46:34.588 3580-3773/com.example.weex.hackernews E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
> 12-30 14:46:34.589 3580-3773/com.example.weex.hackernews E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
> 12-30 14:46:34.590 3580-3773/com.example.weex.hackernews E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
> 12-30 14:46:34.592 3580-3773/com.example.weex.hackernews E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
> 12-30 14:46:34.605 3580-3773/com.example.weex.hackernews E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
> 12-30 14:46:34.611 3580-3773/com.example.weex.hackernews E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
> 12-30 14:46:34.611 3580-3773/com.example.weex.hackernews E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
> 12-30 14:46:34.612 3580-3773/com.example.weex.hackernews E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
> 12-30 14:46:34.840 3580-3780/com.example.weex.hackernews E/EGL_emulation: tid 3780: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
> 12-30 14:48:48.735 3580-3780/com.example.weex.hackernews E/EGL_emulation: tid 3780: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)

Thanks for you work :)

**Comment by Hanks10100** [comment]
@PymZoR My Android project works well. maybe its something wrong with `DebugServerProxy`, seems `weex-toolkit` rely on it.

**Comment by PymZoR** [comment]
Tried it without success. Perhaps this is a consequence of an "incorrect bundle" generated by the problems cited on #4 ?

**Comment by Jinjiang** [comment]
Hi @PymZoR which version of node & npm (or yarn) you use? Maybe it's related with some environment. Thanks.

**Comment by PymZoR** [comment]
@Jinjiang 
> Node v7.3.0
> Npm 4.0.5
> macOS Sierra

Built with a fresh clone and `npm install` of the project. Only difference to make the weex build to work, is the `weex-vue-loader` added to the loaders, as mentioned in #4.

**Comment by Jinjiang** [comment]
Reproduced. It's about npm version. I will fix it asap.
Thanks.

**Comment by Jinjiang** [comment]
I have bumped `weex-vue-loader@0.2.4` with which `weex-loader` depends. It works for me now. Please have a check.

**Comment by PymZoR** [comment]
It's working perfectly. Good job !

**Comment by alitong** [comment]
you add      compile 'com.taobao.android:weex_inspector:0.8.0.0'
