### ISSUE TITLE
unable to communicate between an element and it's child loaded using <embed>

### ISSUE THREAD

**Issue by venkatesh3007** [weexteam/weex-hackernews#15]
# Parent - 
```
<template>
  <div>
    <text onclick="sayHello">Say Hello</text>
    <embed id="foo" src="child_url.js"></embed>
  </div>
</template>

<script>
  module.exports = {
      methods: { 
         sayHello: function () { 
            var foo = this.$vm("foo");
            foo.hello();
         }
      }
  }
</script>
```
# child_url.js
```
<template>
  <div>
    <text>Child Element</text>
  </div>
</template>

<script>
    module.exports = { 
       methods: { 
          hello: function () {
             console.log("Hello!");
          }
       }
   }
</script>
```

**Comment by Jinjiang** [comment]
Some details:

* `this.$vm('xxx')` is the old Weex syntax, not Vue syntax. It's a little like `this.$refs.xxx` in Vue 2.0
* I guess what you want is sub component. It could be done with custom element, not `<embed>` (`<embed>` is used for a Weex page inside another just like `<iframe>` in web).

*Notice that all the usage above is old Weex syntax. We have already support Vue 2.0 (taking hackernews for example).*

So it could be:

main

```
<template>
  <div>
    <text onclick="sayHello">Say Hello</text>
    <child id="foo"></child>
  </div>
</template>

<script>
  module.exports = {
      methods: { 
         sayHello: function () { 
            var foo = this.$vm("foo");
            foo.hello();
         }
      }
  }
</script>
```
`child.we`

```
<template>
  <div>
    <text>Child Element</text>
  </div>
</template>

<script>
    module.exports = { 
       methods: { 
          hello: function () {
             console.log("Hello!");
          }
       }
   }
</script>
```

An online preview is http://dotwe.org/16cbcdc472383e4983c735d31ed89c8f

Thanks.

**Comment by venkatesh3007** [comment]
@Jinjiang - I could do it using component. Wanted to communicate with the page rendered using <embed>.

**Comment by Jinjiang** [comment]
Gotcha, we can use `BroadcastChannel` API to do this job. We have made the polyfill a few days ago https://github.com/alibaba/weex/issues/1536

**Comment by venkatesh3007** [comment]
Thanks @Jinjiang.
