### ISSUE TITLE
Can't find variable: weex

### ISSUE THREAD

**Issue by 312362115** [weexteam/weex-hackernews#16]
how to fix?

**Comment by 312362115** [comment]
折腾了两天. 发现用这个git库下载的项目, 打包JS,  运行ios. 是ok的. 
然后, 我用pod更新了下weexSDK, 改成了 `pod 'WeexSDK', '~> 0.9.4'` , 用pod导入的最新的SDK, 删掉了自带的SDK, 再次运行, 还是刚才的JS文件, 又出现了  `Can't find variable: weex` 的问题.
所以这是pod上的WeexSDK有问题嘛? 并且我自己创建的项目, 导入了这个git库自带的weexSDK之后, 也正常的可以显示. @Hanks10100

**Comment by 312362115** [comment]
搞清楚了.... pod安装weexSDK后, 还需要手动添加main.js(在WeexSDK.framework包中).......添加后就正常了..

**Comment by 312362115** [comment]
原本是pod导入的SDK, 改成手动导入, 并且
在other link flag添加`-ObjC`, `-l"stdc++",
在copy bundle resources里面添加上WeexSDK framework里面的main.js,
导入依赖的库: AVFoundation, Security, ImageIO, CFNetwork, JavaScriptCore, GLKit, Foundation, CoreData, AVFoundation, libicucore.tbd, AVKit, MediaPlayer, CoreMedia之后, 一切正常..
why?

**Comment by 312362115** [comment]
并且从weex官方下载的0.9.4的framework也不可用, 之后这个demo带得weex的SDK导入后才可用

**Comment by 312362115** [comment]
@Hanks10100

**Comment by Hanks10100** [comment]
The WeexSDK in this project is my own revision, it's much newer than 0.9.4, and has more features.

We are now release [0.9.5](https://github.com/alibaba/weex/releases/tag/v0.9.5), it support the Vue, and has `weex` param.

**Comment by 312362115** [comment]
I found this issue: https://github.com/alibaba/weex/issues/2237 
WeexSDK for ios v0.9.5 中main.js版本滞后 #2237

**Comment by 312362115** [comment]
use the lastest version is work..
