### ISSUE TITLE
启动应用不能正常显示界面

### ISSUE THREAD

**Issue by MrLiHong** [weexteam/weex-hackernews#26]
macOS:10.12.1
Xcode 8.2.1
iPhone6模拟器 10.2
![simulator screen shot 2017 1 21 12 00 36](https://cloud.githubusercontent.com/assets/20055964/22171798/44a49f4c-dfd1-11e6-85eb-4921f3c0a273.png)

日志:
![snip20170121_1](https://cloud.githubusercontent.com/assets/20055964/22171830/2760da1c-dfd2-11e6-8a97-8509901ccf15.png)

**Comment by aleksichen** [comment]
+1

**Comment by aleksichen** [comment]
使用项目自带的/assets/index.js可以正常渲染，但是webpack build 出来的index.weex.js不能正确渲染

**Comment by jjjachyty** [comment]
同样的问题 web可以 ios 不能请求数据
