### ISSUE TITLE
这个项目怎么结合 weex playground  生成qr进行测试

### ISSUE THREAD

**Issue by kingyang** [weexteam/weex-hackernews#32]
如题:
怎么方式通过weex debug --qr 生成二维码 通过 weex playground 进行测试

**Comment by Hanks10100** [comment]
`npm run build` 之后会生成针对 native 平台可用的 js bundle。然后你在本地起一个服务，让手机能访问的生成的 js bundle 就可以了，二维码可以用其他平台生成。

0. 首先执行 `npm run build`，
0. 然后执行 `npm run serve` 会启动服务监听 1337 端口。
0. 用工具或其他在线平台把下边的字符串生成二维码（把 `YOUR_IP` 改成你机器的 IP）：

```
http://whatever.cn?_wx_tpl=http://YOUR_IP:1337/dist/index.weex.js
```

**Comment by justingosan** [comment]
How do you generate the qr code or enter the url manually in the playground app?

**Comment by Hanks10100** [comment]
As I said before (but it's in Chinese), you can start an serve on your local machine, and change the `YOUR_IP` in the above url to the IP which your playground app can assess.

It's annoying to generate QR code in that way. However I also have another tricky way to achieve it.

I have already copy the js bundle to the `android` and `ios` folder, so you can use those **raw** file on github to generate QR code. ([in andorid](https://raw.githubusercontent.com/weexteam/weex-hackernews/master/android/app/src/main/assets/index.js) [in ios](https://raw.githubusercontent.com/weexteam/weex-hackernews/master/ios/assets/index.js))

Take ios as example, you can use this url to generate the QR code by any tools.

```
http://whatever.cn?_wx_tpl=https://raw.githubusercontent.com/weexteam/weex-hackernews/master/ios/assets/index.js
```

**Comment by Hanks10100** [comment]
Well, I just put the QR code here. (It's not very stable)

![static_qr_code_without_logo](https://cloud.githubusercontent.com/assets/8401776/23333360/49e3b26c-fbc5-11e6-8c85-c4d65eaaa4b5.jpg)
