### ISSUE TITLE
用什么命令打包android和ios?

### ISSUE THREAD

**Issue by mzl1988** [weexteam/weex-hackernews#33]

**Comment by gengjiawen** [comment]
Android的话打包用Android Studio打包方便点，命令行的话，android打包执行`cd android && ./gradlew assembleDebug`.

**Comment by Hanks10100** [comment]
@mzl1988 在安卓上用 @gengjiawen 说的方法就可以，iOS 下用 Xcode 打开项目，选择目标设备后，有按钮可以直接 build，不过如果想 build 到真机的话，还得配开发者签名（自己机器上可以建一个 Personal Team）。

另外还有个自动打包的工具 [weex-pack](https://github.com/weexteam/weex-pack) ，它可以初始化并且打包项目。不过这个项目是我手动初始化的，结构和 weex-pack 自动生成的项目有些不太一样，建议用 Xcode 和 Android Studio 打包。
