### ISSUE TITLE
看过代码后的疑问

### ISSUE THREAD

**Issue by hodgevk** [weexteam/weex-hackernews#34]
我研读了hackernews的代码，如果使用了vue+vuex+router的话，其实app就是个单页应用，weex instance实例只有一个，不知道我这么理解是否正确。

**Comment by Hanks10100** [comment]
对的，这个应用可以视为单页应用，Weex 的实例在 Web 上是和“浏览器页签”的概念相对应的，虽然用了 vue-router 但是依然在同一个 Weex 实例中。

另外，因为 vue-router 的设计和实现都是在同一个页面内的，是 SPA 概念里的产物。其实前端路由也是基于 SPA 产生的概念，在 Weex 或者原生应用这种多页跳转的场景里可能并不合适，慎重使用。

要想在原生页面之间（Weex 多实例之间）跳转，可以使用 [`navigator`](https://weex-project.io/cn/references/modules/navigator.html) 模块，也可以看看 [weex-router](http://market.dotwe.org/ext/list.htm#9)。

**Comment by hodgevk** [comment]
谢谢，明白了。
