### ISSUE TITLE
ERROR ：component lists rendered with v-for should have explicit keys

### ISSUE THREAD

**Issue by rainwalkerhu** [weexteam/weex-hackernews#37]
改完对应的文件，重新执行npm run dev还是报相同的错误，貌似根本不识别我的更改，项目也不提供清除缓存命令，手动删除dist文件夹没用，点解？

**Comment by Hanks10100** [comment]
是 Vue 最近的改动，写 `v-for` 不写 `key` 就会警告 https://github.com/vuejs/vue/commit/5ae63d9d2f6a6bc58d43a2260ec9e0c647af6392
