### ISSUE TITLE
工程web端如何热加载？

### ISSUE THREAD

**Issue by giticaniup** [weexteam/weex-hackernews#38]
如题。npm run serve后修改代码不能热加载

**Comment by motcwang** [comment]
使用webpack-dev-server应该就可以了吧

**Comment by Hanks10100** [comment]
用 `webpack-dev-middleware` 和 `webpack-hot-middleware` 可以实现 hot-reload ，不过这是个模板项目，不想配置的太过复杂。

具体配置方法可以用 `vue-cli` 生成一个 Webpack 的项目看一下里边的配置。
