### ISSUE TITLE
npm run build报错

### ISSUE THREAD

**Issue by lwfyiwei** [weexteam/weex-hackernews#4]
![image](https://cloud.githubusercontent.com/assets/22360070/21340693/355d2364-c6c3-11e6-958b-82624e9f2ddc.png)

**Comment by yjj5855** [comment]
一样 weex-loader 这个包不对

**Comment by alwayrun** [comment]
```bash
├── babel-core@6.21.0
├── babel-loader@6.2.10
├── babel-plugin-transform-runtime@6.15.0
├── babel-preset-es2015@6.18.0
├── babel-runtime@6.20.0
├── css-loader@0.26.1
├── serve@1.4.0
├── vue@2.1.6
├── vue-loader@10.0.2
├── vue-router@2.1.1
├── vue-template-compiler@2.1.6
├── vuex@2.1.1
├── vuex-router-sync@4.0.2
├── webpack@1.14.0
├── weex-loader@0.4.0
└── weex-vue-render@0.1.0-beta.2
```
npm run build:weex

<img src="https://cloud.githubusercontent.com/assets/22360070/21340693/355d2364-c6c3-11e6-958b-82624e9f2ddc.png" />

**Comment by alwayrun** [comment]
@yjj5855  @lwfyiwei 
你们这个问题解决了吗?

**Comment by alwayrun** [comment]
```bash
我在 node 4.0.0 上执行 npm run build:week 是没问题，估计是在高版本的node上npm扁平之后的原因
```

**Comment by yjj5855** [comment]
@alwayrun  node 6  npm 3

**Comment by WalterZou** [comment]
同样有这个问题...

**Comment by gary149** [comment]
solution anyone ?

**Comment by Jinjiang** [comment]
我看一下

**Comment by ianchenyangzhao** [comment]
和这个issue是一样的。
[https://github.com/weexteam/weex-loader/issues/39](url)
我目前是
node v7.2.9
npm v3.10.9

**Comment by ianchenyangzhao** [comment]
@Jinjiang 我对`webpack.weex.config.js`做了些修改，在载入｀weex-loader`之前，载入`vue-loader`对Vue文件进行编译，然后整个编译就顺利通过了。

```
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      }, {
        test: /\.vue(\?[^?]+)?$/,
        loaders: ['weex-loader']
      }, {
        test: /\.vue(\?[^?]+)?$/,
        loaders: ['vue-loader']
      }
    ]
  }
```

**Comment by ianchenyangzhao** [comment]
But I think we still need to update webpack config files. The output index.weex.js uses `Vue` instance, when copied to `ios/assets` and build on device will throw exception `ReferenceError: Can't find variable: Vue`. 
I'm using `weex-loader@0.4.1`

**Comment by Hanks10100** [comment]
> Sorry about the confusions. This app is under development, the code in master branch may not always new. It's my fault.

The webpack config works well in my env. I will check the compatibility of `weex-loader`. Although `weex-loader` support to compile `.vue` files, but the `weex-vue-loader` should also be installed.

**Comment by IanZhao** [comment]
Thank you for all the hard work @Hanks10100. I'll update my env and add weex-vue-loader to the loader modules. See if this helps.

**Comment by Jinjiang** [comment]
It seems work well in latest master commit

**Comment by WalterZou** [comment]
Well, pulled the lastest code just now, it seems still has this problem.
![image](https://cloud.githubusercontent.com/assets/3727208/21561887/11cb483e-ceae-11e6-91e8-d24342aac366.png)
My dev environment: 
```
Window 10
Node v7.3.0
NPM 4.0.5
```

**Comment by PymZoR** [comment]
Exact same problem as @WalterZou here.
Environment:

> macOS 10.12
> Node v7.3.0  
> npm 4.0.5

**Comment by PymZoR** [comment]
I guess vue-weex-loader still needs to be added in the webpack config
`loaders: ['weex-loader', 'weex-vue-loader']`

**Comment by Hanks10100** [comment]
@PymZoR It should works well with only `weex-loader`, and I can't trigger that error on my env (node v6.6.0).

Anyway, I will add `weex-vue-loader` in webpack config until I found the reason of this bizarre behavior.

**Comment by Jinjiang** [comment]
I have make a update for `weex-vue-loader`. And now we don't need to write it into `devDeps` directly because `weex-loader` requires it.
It works well at this time.
Thanks.
