### ISSUE TITLE
Vue中使用image/img显示不了图片

### ISSUE THREAD

**Issue by motcwang** [weexteam/weex-hackernews#40]
移动端是可以的，浏览器里面图片显示不出来，感觉可能是解析的问题

**Comment by Hanks10100** [comment]
有没有具体的代码？ 在 http://dotwe.org/vue 上写个例子吧。

**Comment by motcwang** [comment]
http://dotwe.org/vue/702fc26ad25f833ba77d72c72401d0d0
就是最简单的代码，因为是三端使用，所以在web端使用的是vue-loader编译的
```
<template>
    <div>
        <img src="https://img.alicdn.com/tps/TB1z.55OFXXXXcLXXXXXXXXXXXX-560-560.jpg" style="width: 560;height: 560;"></image>
    </div>
</template>
```

**Comment by Hanks10100** [comment]
@motcwang 给图片宽高加上单位就行了 http://dotwe.org/vue/c4d537a000aa52b4de0e72557114c502
