### ISSUE TITLE
这个demo能包含Weex Playground App里面例子的代码吗？

### ISSUE THREAD

**Issue by simonwu-os** [weexteam/weex-hackernews#41]
看了一下 Weex Playground App,里面有些demo的例子想参照用，但没有找到任何参考代码。问一下这个demo能包含 Weex Playground App里面的demo的代码吗？谢谢

**Comment by ChengRuipeng** [comment]
同问。

**Comment by JackPu** [comment]
@ChengRuipeng  参考代码： https://github.com/apache/incubator-weex/tree/master/examples/vue

**Comment by Hanks10100** [comment]
这个项目只写 Hacker News 这个项目，不放其他 demo。Playground App 里的代码参考 @JackPu 贴出来的链接。

另外我还有个 [weex-vue-examples](https://github.com/Hanks10100/weex-vue-examples) 的项目，里边含了各种各样的 demo。

**Comment by JackPu** [comment]
@ChengRuipeng  我也贴个weexpack工程参考项目代码仅供参考: 
[weex-app-seed]([![npm](https://img.shields.io/npm/v/weex-app-seed.svg?maxAge=2592000)]()
)

**Comment by simonwu-os** [comment]
@Hanks10100 @JackPu Thanks very much

**Comment by simonwu-os** [comment]
@Hanks10100  我提了一个issue针对weex v0.10 。 [关于list控件不能用loading的子控件的问题](https://github.com/Hanks10100/weex-vue-examples/issues/3)，list控件不能调用loading的@loading的事件。list自己的@loadmore是可以工作的，但不能加loading子控件。
