### ISSUE TITLE
pod install 时，Operation not supported on socket 错误

### ISSUE THREAD

**Issue by nicefan** [weexteam/weex-hackernews#42]
Errno::EOPNOTSUPP - Operation not supported on socket - (../../../SDWebImage/SDWebImage/NSData+ImageContentType.h, /Volumes/VMware Shared Folders/workspace/weex-pula/ios/Pods/Headers/Private/SDWebImage/NSData+ImageContentType.h)

**Comment by Hanks10100** [comment]
我帮你网上搜了一下，找到了这个 issue https://github.com/CocoaPods/CocoaPods/issues/4641

可能是你本地环境 VMware 配置的问题，报错的文件不在这个项目内。

**Comment by nicefan** [comment]
@Hanks10100 感谢，的确是路径的问题，已解决，现在有个上传图像的问题，麻烦请教一下。
我没有找到一个三方通用的模块，可以使用，然后我用Web组件，嵌入一个上传图片的html,在iOS端可以使用，可是在Android上点击没有任何效果。请问有什么好的办法可以解决吗？
