### ISSUE TITLE
ReportException : ReferenceError: Vue is not defined

### ISSUE THREAD

**Issue by tonyyls** [weexteam/weex-hackernews#43]
将示例编译出index.weex.js 放在android的 assets目录下，报：ReportException : ReferenceError: Vue is not defined。  在chrome的开发人员工具下是正常的。 工程没做任何改动。

**Comment by Hanks10100** [comment]
确认一下 index.weex.js 文件里，最上边的注释还在不在。要有这个注释才会被 Vue 框架渲染的。

```js
// { "framework": "Vue" }
```

**Comment by gangzi828** [comment]
我也是同样的问题，求解答！

**Comment by xieningtao** [comment]
com.taobao.android:weex_sdk:0.10.0
使用这个版本就ok了
