### ISSUE TITLE
有没有组件可供使用？像weex官方给的vue的examples

### ISSUE THREAD

**Issue by yukailis** [weexteam/weex-hackernews#44]

**Comment by Hanks10100** [comment]
不太明白你说的`“有没有组件可供使用”`是什么意思，我用的是 `weex-vue-render` 里的组件。这个项目本身就是个 example ，源码都在这个仓库里。

**Comment by bruceclxu** [comment]
这东西怎么 移动端debug？

**Comment by JackPu** [comment]
@bruceclxu 是指 移动端真机调试么？ 可以使用 [weex-toolkit](https://github.com/weexteam/weex-toolkit) 中的 `weex debug ` 调试文件。
