### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by xinayida** [weexteam/weex-hackernews#45]
运行npm run build报错
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].output.path: The provided value "dist" is not an absolute path!

 - configuration[1].output.path: The provided value "dist" is not an absolute path!

**Comment by Hanks10100** [comment]
项目是用 Webpack 2 编译的，请确保你的版本正确，可以删掉 `node_modules` 再重新安装。

如果还报错，贴一下你用的 node 和 Webpack 的版本。

**Comment by laobaigan** [comment]
把webpack.config.js里面的 output 改成
 output: {
      path: path.resolve('./dist'),
    },试试

**Comment by niyaoyao** [comment]
@laobaiganThanks! It's work for me : ) 👍
