### ISSUE TITLE
Never installed Vuex in Web

### ISSUE THREAD

**Issue by galenyuan** [weexteam/weex-hackernews#47]
https://github.com/weexteam/weex-hackernews/blob/master/src/store/index.js#L7
This line should be
```javascript
if (WXEnvironment.platform === 'Web') {
  Vue.use(Vuex)
}
```

**Comment by galenyuan** [comment]
hmm, why contained `Vue.use(Vuex)` in IfStatement?
I think both Web and Weex need to install Vuex first

**Comment by Hanks10100** [comment]
Because the `Vuex` is auto installed on the web. https://github.com/vuejs/vuex/blob/v2.2.1/src/store.js#L426-L429

This code works for me on the web.

**Comment by galenyuan** [comment]
😂 make sense
