### ISSUE TITLE
我怎么来生成 android 和 ios 目录 像这个一样

### ISSUE THREAD

**Issue by manman1992** [weexteam/weex-hackernews#48]
利用weex pack 和 Weex-Toolkit 都没办法做到呢

**Comment by Hanks10100** [comment]
开始做这个项目的时候 weex-pack 还不够完善，我是自己手动创建的 iOS 和 Android 项目，简略过程参考  #1 和 #2 。

现在 **weex-pack** 和 weex-toolkit 都支持创建 Android 和 iOS 项目，具体用法参考 [weex-pack README](https://github.com/weexteam/weex-pack#weexpack-介绍)。

```
# 使用weexpack 命令
$ weexpack platform add ios

# 使用weex-toolkit
$ weex platform add  ios
```

**Comment by manman1992** [comment]
好滴 谢谢 hanks
