### ISSUE TITLE
weex is not defined in android app

### ISSUE THREAD

**Issue by venkatesh3007** [weexteam/weex-hackernews#5]
When I run the android app, I get the below error:
  
`E/weex: reportJSException >>>> instanceId:1, exception function:createInstance, exception:ReferenceError: weex is not defined`

it's thrown because of the line `const stream = weex.require('stream')` in the file src/store/fetch.js

**Comment by Jinjiang** [comment]
Which app and version it is? `weex.require` is a very new API. Maybe the version is a little old.

**Comment by Hanks10100** [comment]
> Sorry about the confusions. This app is under development, the code in master branch may not always new. It's my fault.

After I upgrade the version of js framework in WeexSDK, This would be fixed.

**Comment by Hanks10100** [comment]
@venkatesh3007 I have already upgrade the version :)

**Comment by venkatesh3007** [comment]
@Hanks10100 Yeah. Checked it. This error is gone so closing it.
