### ISSUE TITLE
拷贝 bundle 文件，这一步，不是简单的拷贝吧。

### ISSUE THREAD

**Issue by chenkezhao** [weexteam/weex-hackernews#51]
"copy:android": "cp dist/index.weex.js android/app/src/main/assets/index.js",

index.weex.js和index.js内容明显不同的啊。

index.js是怎么生成的呢？

用weex src --entry src/App.vue启动，[Weex Playground App]访问是空白的。

**Comment by Hanks10100** [comment]
拷贝到 android 和 ios 目录下的文件是压缩后的。（我在 webpack.config.js 里加了压缩代码的命令，又注释掉了）

这各项目不是用 weex-toolkit 创建出来的，不要直接用 `weex` 命令启动；自己生成二维码，然后用 playground app 扫码打开。
