### ISSUE TITLE
how to use local image file?

### ISSUE THREAD

**Issue by simonwu-os** [weexteam/weex-hackernews#52]
in weex, how to use local image file? so we can use it in h5 and android project.

**Comment by Hanks10100** [comment]
Configure the path of assets in the Xcode and the Android Studio project, then you can use local image files.

**Comment by 2solidtechnologies** [comment]
can you explain a bit more?

**Comment by shinriyo** [comment]
I can't

**Comment by zmobs** [comment]
> in weex, how to use local image file? so we can use it in h5 and android project.

we use local image, with a module named imageadapter.   the imageadapter module router the image url to a real android res

**Comment by shinriyo** [comment]
@Hanks10100 How to use?


# js

```
  data() {
    return {
      logo: "https://vuejs.org/images/logo.png",
```

# Pug

```
image.logo(style='width:500px;height:500px', :src='logo')
```

It works

But, local can't

**Comment by shinriyo** [comment]
fm...
https://www.base64-image.de
I convert via the web site.
And used the converted base64 string. hahaha

**Comment by Hanks10100** [comment]
@shinriyo Maybe you can also try this: http://weex-project.io/guide/advanced/path.html

**Comment by shinriyo** [comment]
@Hanks10100 Thank you fore response.
However, I already read the document.
The document is not kind.
I tried a lot.

What I don't understand is "where should I put image file?", "should I write extension" and "should I make assets or images directory".

It is my `data()` property
```
  data() {
    return {
      // logo: 'local:///assets/images/logo',
      // logo: 'local:///assets/images/logo',
      // logo: 'local:///assets/images/logo.png',
      // logo: 'local:///logo',
      logo: 'local:///logo.png',
    };
  }
```

It is my pug code.
```
<template lang="pug">
div
  image.logo(style='width:672px;height:292px', :src='logo')
```

My Path is ...

`src/assets/images/logo.png`

**Comment by Hanks10100** [comment]
Actually, you should put your image files into the Android Studio or Xcode project, the *native* project, not the source code of front-end project.

Here are some links I searched:
https://stackoverflow.com/questions/18302603/where-do-i-place-the-assets-folder-in-android-studio
https://guides.codepath.com/ios/adding-image-assets

> Sorry for the poor documentation, we are working on improving it.
