### ISSUE TITLE
请问你为何不用weex自己的语法，使用.we文件呢？能谈谈你的看法吗？

### ISSUE THREAD

**Issue by MGXu** [weexteam/weex-hackernews#53]

**Comment by Hanks10100** [comment]
这个项目就是一个使用 Vue.js 的范例项目，首要目的就是要用 Vue.js 。

另外 `.we` 语法已经废弃，Weex 和 Vue.js 有官方合作，建议从 `.we` 过渡到 `.vue` 语法。

**Comment by MGXu** [comment]
weex 只是目前支持vue 2.0 没有打算把自己的语法废了的打算吧？

**Comment by Hanks10100** [comment]
@MGXu `.we` 语法借鉴自 Vue 1.0 ，现在既然官方支持 Vue 2.0 了，旧版语法自然要逐渐废弃。

如果你打算写个新项目，建议直接用 `Vue 2.0`；如果你已经有了 `.we` 的项目，建议用 [weex-vue-migration](https://github.com/songsiqi/weex-vue-migration) 工具辅助升级到 Vue 2.0。

**Comment by MGXu** [comment]
感谢你的回复，那要是用vue 2.0是不是直接去vue 的官网学了？还是weex现在官网的语法示例就是用的Vue 2.0写的？

**Comment by Hanks10100** [comment]
是的。

+ Weex 中文官网： http://weex.apache.org/cn/
+ Vue.js 中文官网：https://cn.vuejs.org/
