### ISSUE TITLE
what'the diff between <weex compile> and <webpack>

### ISSUE THREAD

**Issue by InterfaceYang** [weexteam/weex-hackernews#54]
好吧，写个英语标题是为了吸引人过来。我用webpack打包后的JS文件在IOS端不能正常使用，但weex compile就可以。想知道。为什么不行/

**Comment by Hanks10100** [comment]
你只说了不正常，我也猜不出来原因。这类问题与本仓库无关，可以在 Weex 社区里提问。建议提问时更详细的描述一下问题和复现过程 : )

+ [weex-pack 文档](https://github.com/weexteam/weex-pack/blob/master/README.md)
+ [weex-toolkit 文档](https://github.com/weexteam/weex-toolkit/blob/dev/README-zh.md)
