### ISSUE TITLE
pullingdown方法调用之后，就会一直执行。不应该只是在pullingdown那一瞬间执行吗，或者我打开方式不对？求教

### ISSUE THREAD

**Issue by InterfaceYang** [weexteam/weex-hackernews#55]
onpullingdown (event) {
                   modal.toast({
                        message:event.pullingDistance
                   })
                }

**Comment by Hanks10100** [comment]
这类问题与本仓库无关，可以在 Weex 社区里提问 : )

+ 中文： [SegmentFault](https://segmentfault.com/t/weex)
+ 英文： [StackOverflow](http://stackoverflow.com/questions/tagged/weex)
+ [邮件列表](http://mail-archives.apache.org/mod_mbox/incubator-weex-dev/)
