### ISSUE TITLE
写的we文件，用weex debug 调试，在playground上扫码正常，但是在ios上异常，求教，在IOS上打包有什么注意事项吗

### ISSUE THREAD

**Issue by InterfaceYang** [weexteam/weex-hackernews#56]
`<list>
<cell v-for="dept in depts"  index="{{$index}}">
              <div class="header">
                <text class="header-title">{{dept.name}}</text>
             </div> 
<cell>
</list>`
就是上边这个动态拼接的list
详细说下
数据获取方式：created里边数据获取。在计算属性中数据清洗，返回对象列表数组depts。
在data里已经定义  detps=[]。
打包方式：开始的时候使用weebpack 的weex-loader。同样在playground可显示，ios端不行。
引用方式：传到静态服务器，https：
想了解，weex是否跟vue似的存在数据双向绑定？开始这样写<cell repeat='dept  in depts'>也不行。

**Comment by InterfaceYang** [comment]
@Hanks10100 求教大神。如果有什么说的不清楚，随时问我。。

**Comment by Hanks10100** [comment]
**问题与本项目无关，请去 Weex 社区里提问。**

在 http://dotwe.org/vue 上可以提供完整的例子，建议提问时描述一下 iOS 有什么异常。
