### ISSUE TITLE
为什么不加分号？为什么不加分号？为什么不加分号？

### ISSUE THREAD

**Issue by SteveCruise** [weexteam/weex-hackernews#58]
为什么每行结尾不加分号？为什么？

**Comment by Hanks10100** [comment]
个人习惯而已。

**Comment by SteveCruise** [comment]
Webstorm推荐加分号，不加会警告。Webstorm推荐4个空格，可以一键规整格式，等等。唉，算了

**Comment by zhuweiyou** [comment]
为什么要加分号？

![image](https://user-images.githubusercontent.com/8413791/31924372-4b7ffe8a-b846-11e7-9d9f-50b204c86808.png)
