### ISSUE TITLE
单页ios 返回问题

### ISSUE THREAD

**Issue by aoping** [weexteam/weex-hackernews#59]
请问在iOS上怎么一页一页返回呢,而不是一次退出hybrid页面

**Comment by Hanks10100** [comment]
目前还不支持，使用 [navigator 模块](http://weex.apache.org/cn/references/modules/navigator.html) 可以实现。

**Comment by lovederh** [comment]
xcode编译时报 Apple Mach-O Linker Error Linker command failed width exit code 1(use -v to see invocation)

**Comment by yuanlove521** [comment]
@lovederh 是打开的文件错误

**Comment by s249359986** [comment]
@Hanks10100 我使用了navigator 模块 ，但发现使用两次以上push方法进行跳转，只能回退一次？

**Comment by aoping** [comment]
weex playground ios的bug, 一直存在没有修复，换个壳就不会了

**Comment by s249359986** [comment]
@aoping 下载最新的weex playground 依旧存在问题。你们官方给的导航例子也存在这个问题

**Comment by Hanks10100** [comment]
@s249359986 如果确认有问题，希望能提供一个能复现的例子和对应的版本。可以给
 Weex 邮件列表（dev@weex.incubator.apache.org）发邮件讨论，或者[在 Weex 仓库里提 issue](https://issues.apache.org/jira/projects/WEEX/issues)。
