### ISSUE TITLE
[suggest] make different actions for clicking external links between web and native

### ISSUE THREAD

**Issue by Jinjiang** [weexteam/weex-hackernews#6]
When user click an external link:

* in web: open a new tab with the url of external link
* in native: open a fullscreen `<web>` component and a back button

**Comment by Blueblau** [comment]
Is there a way you can do this manually by now, before this suggestion might be implemented?

**Comment by Jinjiang** [comment]
I can make a custom component to encapsulate these two different ways into one tag (like `<external-link>`) together.

**Comment by Jinjiang** [comment]
fixed https://github.com/weexteam/weex-hackernews/commit/4bbb71c7fe38da514f326d51b152f6fc6626d1c2
