### ISSUE TITLE
这是基于weex init 还是weex create的框架

### ISSUE THREAD

**Issue by sunsunyongjiu** [weexteam/weex-hackernews#60]
为什么项目结构不同于两种框架的初始模板，官网不能提供一个详细的学习稳当么？初始化以后完全不知道怎么改造项目，怎么引入vue router等，对新人很不友好

**Comment by Hanks10100** [comment]
可以参考系列文章：[《使用 Weex 和 Vue 开发原生应用》](https://segmentfault.com/a/1190000008342533)，里边详细介绍了这个项目的各个细节。

刚开始写这个项目的时候，Weex 还不支持用 Vue.js ，工具也都不支持，项目是手动搭建的，参考 #1 和 #2 。

**Comment by zero7u** [comment]
为什么不更新文档，学起来很困惑，国内开源就这个通病

**Comment by zero7u** [comment]
建议开源playground，开放几个template模板，从零起步的文档，vue文档那样，深入浅出
