### ISSUE TITLE
如何迁移到weex create项目

### ISSUE THREAD

**Issue by zero7u** [weexteam/weex-hackernews#61]
初入weex，带着一颗感恩的心，逛了几天之后，发现`weex-hackernews`应该是最新的最适合入门的模板项目，现在的`weex-toolkit`可以通过`init`和`create`两种方式创建项目，个人感觉`create`可以完全代替`init`，现在的模板项目，属于`weex-toolkit`完善之前就存在的项目，因此像很多新手一样，很想知道`hackernews`项目如何迁移到`weex create`出来的项目，谢谢～

**Comment by lovederh** [comment]
有人维护吗？

**Comment by Hanks10100** [comment]
这个项目不是 weex-pack 创建的项目，因为开发的时候 weex-pack 和 Weex SDK 都还不支持 Vue.js。 参考 https://github.com/weexteam/weex-hackernews/issues/64#issuecomment-333360715 。

迁移的话，用 `weex create` 创建一个项目，把当前项目与 Vue 相关的代码移过去就行了。
