### ISSUE TITLE
android项目跑起来一直显示loading

### ISSUE THREAD

**Issue by lovederh** [weexteam/weex-hackernews#63]
访问不到数据

**Comment by banchichen** [comment]
iOS也是，在pc端访问是正常的...在Weex Playground里一直loading，手机访问github正常

**Comment by Hanks10100** [comment]
不是系统和代码的问题，是网络的问题。这个项目用的是 HackerNews 官方提供的基于 Google 的 [Firebase](https://firebase.google.com/) 提供的服务，国内应该也可以访问但是会慢一些。
