### ISSUE TITLE
在windows平台上运行报错

### ISSUE THREAD

**Issue by longye321** [weexteam/weex-hackernews#65]
我的系统是Windows7 ，使用npm run copy命令报错，提示：‘cp’ 不是内部或外部命令，也不是可运行的程序或批处理文件。
我想问一下，你这个项目是否对windows平台支持的不好

**Comment by Hanks10100** [comment]
这个只是用来把代码拷到指定位置的脚本，不影响本身功能。

建议在 Windows 下安装一些常用的 shell 命令。
