### ISSUE TITLE
在项目里怎么写页面的宽度？是750吗？我写成固定宽度在引入图片的时候，不同设备图片显示不成比例，怎么解决呢

### ISSUE THREAD

**Issue by xiujianyao** [weexteam/weex-hackernews#69]

**Comment by Hanks10100** [comment]
目前宽度 750 是默认配置，可以用 meta 模块的 [`setViewport`](https://weex-project.io/cn/references/modules/meta.html#setViewport-options) 方法修改屏幕宽度。不过这个是对整个页面生效的。

对于图片，可以用 [`load`](https://weex-project.io/cn/references/components/image.html#事件) 事件里取到图片的真实大小，然后应用在图片的样式上。
