### ISSUE TITLE
组件引入图片报错误Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by lovederh** [weexteam/weex-hackernews#70]
<template>
  <div class="header">
    **<div class="logo" @click="jump('/')">
      <image class="image" src="https://news.ycombinator.com/favicon.ico"></image>
    </div>**
    <div class="nav">
      <div class="link" @click="jump('/top')">
        <text class="title">Top</text>
      </div>
      <div class="link" @click="jump('/new')">
        <text class="title">New</text>
      </div>
      <div class="link" @click="jump('/show')">
        <text class="title">Show</text>
      </div>
      <div class="link" @click="jump('/ask')">
        <text class="title">Ask</text>
      </div>
      <div class="link" @click="jump('/job')">
        <text class="title">Job</text>
      </div>
    </div>
  </div>
</template>

<style scoped>
  .header {
    position: relative;
    height: 120px;
    margin-bottom: 3px;
    border-bottom-width: 2px;
    border-bottom-style: solid;
    border-bottom-color: #DDDDDD;
    background-color: #FF6600;
  }
  .logo {
    position: relative;
    width: 50px;
    height: 50px;
    top: 35px;
    left: 35px;
    border-width: 3px;
    border-style: solid;
    border-color: #FFFFFF;
  }
  .image {
    width: 44px;
    height: 44px;
  }
  .nav {
    display: flex;
    position: absolute;
    left: 120px;
    top: 35px;
    flex-direction: row;
    flex-wrap: nowrap;
    justify-content: flex-start;
    align-items: center;
  }
  .link {
    padding-left: 15px;
    padding-right: 15px;
  }
  .title {
    font-family: Verdana, Geneva, sans-serif;
    font-size: 32px;
    line-height: 44px;
    color: #FFFFFF;
  }
</style>

**Comment by Hanks10100** [comment]
看报错信息应该是某些地方存在递归调用，其他看不出来任何有效信息，我本地也没复现问题，是不是改了某地方代码？

**Comment by lovederh** [comment]
@Hanks10100 我也不知道是什么原因，我用weex重新建了一个项目，然后将生成的iOS做了一下替换之后好了！

**Comment by Ayana7** [comment]
扫码浏览数据没加载出来，只有loading...

**Comment by Hanks10100** [comment]
@Ayana7 是网络问题，参考 https://github.com/weexteam/weex-hackernews/issues/63#issuecomment-333361387 。
