### ISSUE TITLE
fetch的远程地址打不开了，能不能把服务器端的json都打包发一份。

### ISSUE THREAD

**Issue by michaelzhouh** [weexteam/weex-hackernews#71]
fetch的远程地址打不开了，能不能把服务器端的json都打包发一份。
非常感谢。

**Comment by Hanks10100** [comment]
数据要动态从网上取的，打包在本地的话就不再是 "News"，就没意义了。

网络用的是 Google 的 [Firebase](https://firebase.google.com/) 提供的服务，国内应该也可以访问但是会慢一些。
