### ISSUE TITLE
使用weex-ui时在android打开不显示任何内容

### ISSUE THREAD

**Issue by Shruan** [weexteam/weex-hackernews#76]
weex-hackernews引用weex-ui组件android界面显示空白，在浏览器上显示正常，
不使用weex-ui时在Android和浏览器均显示正常显示正常。
要想使用weex-ui要进去什么样的配置

**Comment by Hanks10100** [comment]
这个项目并没有使用 weex-ui，如果你想使用 weex-ui 可以单独建个项目，请参考官方仓库里的文档 https://github.com/alibaba/weex-ui
