### ISSUE TITLE
在web端页面在F12下打开Toggle device toolbar页面才可点击加载数据

### ISSUE THREAD

**Issue by DUDUfine** [weexteam/weex-hackernews#78]
您好，在学习你的项目时遇到问题：
浏览器页面在F12下打开Toggle device toolbar页面才可点击加载数据，没有打开F12进入Toggle device toolbar模式点击导航栏及数据项无反应；
在手机直接打开只显示导航栏无数据，点击导航也无反应，
请问这是什么原因可以怎么解决？

**Comment by w469849848** [comment]
json文件拿不到，报错连接超时。
