### ISSUE TITLE
关于IOS 键盘顶起整个界面

### ISSUE THREAD

**Issue by aiooo3838** [weexteam/weex-hackernews#79]
由于项目的导航栏也是使用了weex 做的，如果页面下方有input 焦点事件，整个页面将被顶起，导航栏不见，这样体验很差，但是试过很多方法，都是直接顶起了整个页面。fixed 定位元素也会跟着页面顶起。

**Comment by Hanks10100** [comment]
这项目里使用的 Weex SDK 是基于 2016 年 12 月左右的源码集成的，并非正式版本。建议使用新的正式版 SDK 验证功能。
