### ISSUE TITLE
一直处于loading

### ISSUE THREAD

**Issue by xiaozhuxiong121** [weexteam/weex-hackernews#80]
<img width="1777" alt="2018-01-02 2 44 00" src="https://user-images.githubusercontent.com/7292110/34476407-7c77e9f0-efcb-11e7-86db-c5f80a7598a9.png">

一直处于loading，请问下，是什么原因

**Comment by GeSnowBoy** [comment]
Me too

**Comment by gjterry** [comment]
it's timeout.please use VPN

**Comment by gjterry** [comment]
it's timeout, use VPN and try again
