### ISSUE TITLE
How to use 'mapActions' and 'mapGetters' with vuex?

### ISSUE THREAD

**Issue by arifhussain353** [weexteam/weex-hackernews#81]
Hi, I  am trying to use `mapActions` and `mapGetters` in this project with weex but i am getting following error after following steps:
1 ) `import { mapActions,mapGetters } from 'vuex'`
2 ) 
```
    computed: {
          ...mapGetters(['getProjectHeader']),
      },
```
![image](https://user-images.githubusercontent.com/12670763/34954964-43f0871c-fa44-11e7-9d4e-14c09be51932.png).

Am i missing any step Or we can't use this with weex ?

**Comment by Hanks10100** [comment]
You can use `mapActions` and `mapGetters` in Weex.

According to the error log, I think you are using a wrong syntax of spread operator (`...`).

**Comment by arifhussain353** [comment]
I guess this is the es6 syntax. I am already using this for another vue project.

**Comment by Hanks10100** [comment]
The configure of this project maybe a little *outdate*, you can see much *"modern"* configure in the project which is generated by [weex-toolkit](http://weex-project.io/tools/toolkit.html).
