### ISSUE TITLE
demo的几个调用timeout，只有导航没有内容

### ISSUE THREAD

**Issue by shawn-tangsc** [weexteam/weex-hackernews#82]
askstories.jsonhacker-news.firebaseio.com/v0 | (failed)net::ERR_CONNECTION_TIMED_OUT | xhr | stream.js:143Script | 0 B0 B | 1.1 min-
topstories.jsonhacker-news.firebaseio.com/v0 | (failed)net::ERR_CONNECTION_TIMED_OUT | xhr | stream.js:143Script | 0 B0 B | 1.1 min-
  |   |   |   |

**Comment by zhouhoo** [comment]
maybe the remote server is down or need special rights.

**Comment by Hanks10100** [comment]
This project is using the [Hacker News API](https://github.com/HackerNews/API) which is provided by Google's [Firebase](https://firebase.google.com/), as you know, it may not always stable in China.
