### ISSUE TITLE
怎么将weex sdk 升级到0.16+呢？

### ISSUE THREAD

**Issue by lovederh** [weexteam/weex-hackernews#83]
怎么将weex sdk 升级到0.16+呢？目前想用选取图片的组件，不升级用不了了

**Comment by Hanks10100** [comment]
可以参考这篇文档自己集成 WeexSDK http://weex-project.io/cn/guide/integrate-to-your-app.html

这个项目里的 SDK 是我从仓库源码里拉出来自己打包的。
