### ISSUE TITLE
text标签无法正常显示文字

### ISSUE THREAD

**Issue by shyllb** [weexteam/weex-hackernews#84]

**Comment by shyllb** [comment]
![a e z4jd ni yhatil a 0](https://user-images.githubusercontent.com/14918033/38477830-7cf66bb4-3be7-11e8-9265-5af352721609.png)

**Comment by Hanks10100** [comment]
应该是网络问题，服务用的是 Firebase 提供的，国内不太稳定。参考 https://github.com/weexteam/weex-hackernews/blob/master/README.zh.md#%E9%A2%84%E8%A7%88
